name: musa-550-fall-2022
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy=1.24.0
  - nodejs=18.8
  - black=22.6.0
  - jupyterlab_code_formatter=1.5.3
  - pandas=1.5.2
  - openpyxl=3.0
  - matplotlib=3.6.2
  - notebook=6.4.12
  - ipython=8.4.0
  - jupyterlab=3.4.5
  - nbconvert=7.0.0
  - pip=22.2
  - altair=4.2.0
  - seaborn=0.12.1
  - vega_datasets=0.9.0
  - vega=3.6.0
  - geopandas=0.12.2
  - shapely=2.0.0
  - descartes=1.1.0
  - pyepsg=0.4.0
  - cartopy=0.20.3
  - mapclassify=2.4.3
  - contextily=1.2.0
  - bokeh=2.4.3
  - hvplot=0.8.2
  - holoviews=1.15.3
  - geoviews=1.9.5
  - xarray=2022.6.0
  - datashader=0.14.2
  - param=1.12.3
  - panel=0.14.2
  - rasterio=1.3.2
  - rasterstats=0.17.0
  - earthpy=0.9.4
  - requests=2.28.1
  - cenpy=1.0
  - selenium=4.4.0
  - beautifulsoup4=4.11.1
  - imageio=2.21.1
  - intake=0.6.6
  - intake-parquet=0.2.3
  - intake-xarray=0.6.1
  - dask=2021.8.1
  - fastparquet=0.8.3
  - python-snappy=0.6.0
  - pyarrow=9.0.0
  - s3fs=2022.7.1
  - tqdm=4.64.1
  - pandana=0.6.1
  - osmnet=0.1.6
  - osmnx=1.2.2
  - networkx=2.8.6
  - scikit-learn=1.1.2
  - flask=2.2.2
  - dash=2.6.1
  - tweepy=4.10.1
  - textblob=0.15.3
  - nltk=3.6.7
  - rio-toa=0.3.0
  - rioxarray=0.12.0
  - missingno=0.4.2
  - kneed=0.7.0
  - arcgis2geojson=2.0.1
  - attrs=22.1.0
  - bleach=5.0.1
  - certifi=2022.12.7
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorcet=3.0.1
  - contourpy=1.0.6
  - cycler=0.11.0
  - fiona=1.8.22
  - fonttools=4.38.0
  - idna=3.4
  - importlib-metadata=5.2.0
  - jinja2=3.1.2
  - kiwisolver=1.4.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - munch=2.5.0
  - packaging=22.0
  - pillow=9.3.0
  - pyct=0.4.8
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyviz-comms=2.2.1
  - pyyaml=6.0
  - requests=2.28.1
  - six=1.16.0
  - tornado=6.2
  - typing-extensions=4.4.0
  - urllib3=1.26.13
  - webencodings=0.5.1
  - zipp=3.11.0
  - pip:
      - us==2.0.2
      - webdriver_manager==3.8.4
      - jupyter-panel-proxy==0.1.0
      - jupyter-server-proxy==3.2.1
      - pygeckodriver==0.31.0
      - carto2gpd==1.0.12
      - esri2gpd==1.0.13
