name: musa-550-fall-2022
channels:
  - conda-forge

dependencies:
  - python=3.9
  - jupyter
  - cenpy
  - pyepsg=0.4.0
  - cartopy=0.20.1
  - geoviews=1.9.5
  - mapclassify=2.4.3
  - attrs=22.1.0
  - bleach=5.0.1
  - bokeh=2.4.3
  - certifi=2022.12.7
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorcet=3.0.1
  - contourpy=1.0.6
  - cycler=0.11.0
  - fiona=1.8.22
  - fonttools=4.38.0
  - geopandas=0.12.2
  - holoviews=1.15.3
  - hvplot=0.8.2
  - idna=3.4
  - importlib-metadata=5.2.0
  - jinja2=3.1.2
  - kiwisolver=1.4.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - munch=2.5.0
  - packaging=22.0
  - panel=0.14.2
  - param=1.12.3
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyyaml=6.0
  - requests=2.28.1
  - seaborn=0.12.1
  - shapely=1.8.4
  - six=1.16.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - urllib3=1.26.13
  - webencodings=0.5.1
  - zipp=3.11.0
  - pip
  - pip:
      - carto2gpd==1.0.12
      - esri2gpd==1.0.13
      - arcgis2geojson==2.0.1
      - pillow==9.3.0
      - pyct==0.4.8
      - pyviz-comms==2.2.1

