name: musa-550-fall-2022
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=1.4.3
  - pip=22.2
  - altair=4.2.0
  - seaborn=0.11.2
  - vega=3.6.0
  - geopandas=0.10.2
  - shapely=1.8.4
  - pyepsg=0.4.0
  - cartopy=0.20.3
  - bokeh=2.4.3
  - hvplot=0.8.1
  - holoviews=1.15.0
  - geoviews=1.9.5
  - param=1.12.2
  - panel=0.13.1
  - cenpy=1.0
  - colorcet=3.0.1
  - pip:
      - carto2gpd==1.0.12
      - esri2gpd==1.0.13
  - python=3.9
